name: checkov

# Controls when the workflow will run
on: [ pull_request ]
  #push: 
  #  branches:
  #    - dev_branch_2
  #    - main
  #pull_request:
  #  branches:
  #    - dev_branch_2
  #    - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "scan"
  scan:
    #permissions:
    #  security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    #  actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
      
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false 
      - name: Run Prisma Cloud 
        id: prisma-cloud
        uses: bridgecrewio/checkov-action@master 
        env:
          PRISMA_API_URL: https://api4.prismacloud.io
        with:
          api-key: ${{ secrets.PC_API_KEY }}
          soft_fail: true
          directory: ./
          output_format: cli,sarif
          output_file_path: console,results.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: results.sarif
