name: Deploy Infrastructure

on:
  push:
    branches:
      - main
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  tf_fmt:
    name: Deploy Site
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./tf"
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "us-east-1"
        
    - name: Run Prisma Cloud 
      id: prisma-cloud
      uses: bridgecrewio/checkov-action@master 
      env:
        PRISMA_API_URL: ${{ secrets.PRISMA_API_URL }}
      with:
        api-key: ${{ secrets.PC_API_KEY }}
        soft_fail: true
        directory: ./
        use_enforcement_rules: true
        
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.13.4
        
    - name: Terraform Init
      run: terraform init
      
    - name: Terraform Apply
      run: terraform apply -auto-approve
